name: nlp-project
dependencies:
    - tensorflow
    - keras
    - flask
    - jupyter
    - pip:
        - texsoup
        - docria
        - requests
        - regex
        - neleval
        - git+https://www.github.com/keras-team/keras-contrib.git
        - matplotlib
        - beautifulsoup4
        - seaborn
        - pydot
        - pandas
